/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#0c1323',
        'surface': '#0c1323',
        'surface-container-lowest': '#070e1d',
        'surface-container-low': '#141b2b',
        'surface-container': '#181f2f',
        'surface-container-high': '#232a3a',
        'surface-container-highest': '#2e3545',
        'surface-variant': '#2e3545',
        'surface-bright': '#32394a',
        'surface-dim': '#0c1323',
        'surface-deep': '#07070a',
        'on-surface': '#dbe2f8',
        'on-surface-variant': '#c8c4d8',
        'text-muted': '#666d80',
        'inverse-surface': '#dbe2f8',
        'inverse-on-surface': '#293041',
        'primary': '#c5c0ff',
        'on-primary': '#2500a2',
        'primary-container': '#6453f9',
        'on-primary-container': '#f5f1ff',
        'primary-fixed': '#e3dfff',
        'primary-fixed-dim': '#c5c0ff',
        'inverse-primary': '#533fe8',
        'secondary': '#c8c5cd',
        'secondary-container': '#49484e',
        'on-secondary-container': '#bab7be',
        'secondary-fixed': '#e4e1e9',
        'tertiary': '#ffb68e',
        'tertiary-container': '#b55100',
        'on-tertiary-container': '#ffefe9',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'border-subtle': 'rgba(255, 255, 255, 0.08)',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'stack-sm': '4px',
        'base': '8px',
        'stack-md': '12px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'stack-lg': '24px',
        'margin-desktop': '48px',
        'container-max': '1280px',
      },
      fontFamily: {
        'headline': ['Hanken Grotesk', 'Plus Jakarta Sans', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
